name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: |
          cd care-bear
          npm install

      - name: Run Unit Tests
        run: |
          cd care-bear
          npm run test
      

      - name: Build the Docker image
        run: |
          cd care-bear
          docker build . -t my-svelte-app

      - name: Docker Compose
        run: |
          cd care-bear
          uses: docker/compose-cli-action@v1.5.1
        with:
          compose-file: care-bear/docker-compose.yml
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_body = `Build failed on ${context.ref}`;
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Build Failure",
              body: issue_body
            })

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Super-Linter
        uses: super-linter/super-linter@v5.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: MyDefaultBranch
          DISABLE_ERRORS: true
          OUTPUT_DETAILS: detailed
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_POWERSHELL: false
