name: Deployment Failure Notification

on:
  push:
    branches:
      - main
      - develop
  deployment_status:
    types: [failure]

jobs:
  # Trabajo para verificar la implementación y enviar una notificación en caso de error
  verify-deployment:
    name: Verify Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: Build Application
        run: npm run build

      - name: Deploy to Production
        run: |
          # Aquí puedes agregar comandos para implementar tu aplicación en un servidor de producción
          # Esto dependerá de tu entorno de alojamiento y configuración específica

  # Job to add a commit comment when deployment fails
  add-failure-comment:
    name: Add Commit Comment - Failure
    runs-on: ubuntu-latest

    if: github.event.deployment_status.state == 'failure'

    steps:
      - name: Add commit comment - failure
        run: |
          curl -L -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "body": "Deployment has failed."
          }'
