name: Deployment Notifications
on: [deployment_status]

jobs:
  comment-on-deployment-status:
    name: Comment on the Deployment Status
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    # ... rest of the job steps for success

  add-failure-comment:
    name: Add a comment to the commit that caused the failure
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'failure'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add commit comment - failure
        run: |
          curl -L -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{"body": "Deployment has failed. :x:"}'
